builders:
  spec:
    import: "package:mix_builder/builder.dart"
    builder_factories: ["specDefinition"]
    build_extensions: {".dart": [".spec.dart"]}
    auto_apply: dependents
    build_to: source