name: todo_list
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  mix:
    path: ../../packages/mix
  mix_annotations:
    path: ../../packages/mix_annotations
  custom_lint: ^0.7.5
  google_fonts: ^6.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  mix_generator:
    path: ../../packages/mix_generator
  build_runner: ^2.5.0
  flutter_test:
    sdk: flutter
  mix_lint:
    path: ../../packages/mix_lint

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
