name: "Test Action"
description: "Run DCM and Tests"

on:
  workflow_call:

runs:
  using: "composite"
  steps:
    - name: Checkout mix repo
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: "stable"

    - run: flutter pub get

    - uses: invertase/github-action-dart-analyzer@v1
      with:
        fatal-infos: false

    - name: Install DCM
      uses: CQLabs/setup-dcm@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run DCM
      uses: CQLabs/dcm-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        ci_key: oss
        email: oss
        folders: .
        fatal_style: true
        fatal_performance: true
        fatal_warnings: true
      
    - run: flutter test
