targets:
  $default:
    builders:
      # Enable the consolidated mix_generator builder
      mix_generator|mix:
        enabled: true
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - lib/**/*.g.dart
            - test/**
            - example/**
      
      # Disable individual builders since we're using the consolidated one
      mix_generator|spec:
        enabled: false
      mix_generator|dto:
        enabled: false
      mix_generator|utility:
        enabled: false 