
include: package:flutter_lints/flutter.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: true

analyzer:
  exclude: 
    - "**/*.g.dart"
    - "**/*.freezed.dart"

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  metrics-exclude:
    - test/**
  rules-exclude:
    - "test/**"
  rules:
    prefer-match-file-name: false
    prefer-single-widget-per-file: false
    parameters-ordering: false
    arguments-ordering:
      child-last: true
    avoid-dynamic: false
    avoid-shadowing: false
    prefer-getter-over-method: false
    enum-constants-ordering: false
    prefer-widget-private-members: false
    prefer-static-class: false
    avoid-late-keyword: false
    avoid-barrel-files: false
    avoid-declaring-call-method: false
    avoid-long-parameter-list: false
    avoid-recursive-calls: false
    no-magic-number: false
    avoid-ignoring-return-values: false
    prefer-commenting-analyzer-ignores: false
    prefer-correct-identifier-length: false
    avoid-unsafe-collection-methods: false
    avoid-similar-names: false
    format-comment: false
    no-equal-arguments: false
    prefer_initializing_formals: false
    avoid-nested-conditional-expressions:
        acceptable-level: 3
    member-ordering:
        order:
          - public-fields
          - private-fields
          - constructors
          - static-methods
          - private-methods
          - private-getters
          - private-setters
          - public-getters
          - public-setters
          - public-methods
          - overridden-public-methods
          - overridden-public-getters
          - build-method
    prefer-named-boolean-parameters:
      ignore-single: true


      