# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:flutter_lints/flutter.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: true

analyzer:
dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  rules:
    prefer-match-file-name: false
    prefer-single-widget-per-file: false
  metrics-exclude:
    - test/**