
include: package:flutter_lints/flutter.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: true

analyzer:
  exclude: 
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    


dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  metrics-exclude:
    - test/**
  rules-exclude:
    - "test/**"
  rules:
    prefer-match-file-name: false
    prefer-single-widget-per-file: false
    parameters-ordering: false
    prefer-getter-over-method: false
    prefer-static-class: false
    avoid-late-keyword: false
    avoid-barrel-files: false
    avoid-declaring-call-method: false
    avoid-long-parameter-list: false
    member-ordering:
        alphabetize: true
        order:
          - public-fields
          - private-fields
          - constructors
          - public-getters
          - private-getters
          - public-setters
          - private-setters
          - public-methods
          - private-methods
    prefer-named-boolean-parameters:
      ignore-single: true