targets:
  $default:
    builders:
      your_package_name:spec_definition_builder:
        generate_for:
          - lib/**/*.dart

builders:
  spec_definition_builder:
    import: "package:mix/builder/spec_definition_generator.dart"
    builder_factories: ["specDefinitionBuilder"]
    build_extensions: {".dart": [".spec.g.dart", ".util.g.dart", ".attribute.g.dart"]}
    auto_apply: dependents
    build_to: source
    