targets:
  $default:
    builders:
      your_package_name:spec_definition:
        generate_for:
          - lib/**/*.dart

builders:
  your_package_name:spec_definition:
    import: "package:mix/builder/spec_definition_generator.dart"
    builder_factories: ["specDefinitionBuilder"]
    build_extensions: {".dart": [".spec.g.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]