name: mix_workspace


packages:
  - packages/**
  - examples/**

categories:
  mix_deps:
    - packages/mix
    - packages/mix_annotations
    - packages/mix_generator
  should_test:
    - packages/mix
    - examples/**

scripts:
  brb:
    run: melos exec --scope="mix" -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner for the mix package
  brbc: 
    run: melos exec --scope="mix" --depends-on="build_runner" dart run build_runner clean
    description: Clean build_runner for projects that have it as a dependency
  test:
    run: melos exec --category="should_test" flutter test
    description: Run flutter test in all projects that should be tested
  fix:
    run: melos exec dart fix --apply . &&  melos exec --depends-on="dart_code_metrics_presets" dcm fix .
  analyze:
    run: melos exec --category="mix_deps" dart analyze . && melos exec --category="mix_deps" --depends-on="dart_code_metrics_presets" dcm analyze .