name: mix

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  husky: ^0.1.7
  lint_staged: ^0.5.1
lint_staged:
  '**.dart': 
    - melos run analyze
    - melos run fix
dependencies:
  melos: ^6.3.2
