targets:
  $default:
    builders:
      mix_generator|spec:
        generate_for:
          - lib/**/*_spec.dart
          - lib/**/*_modifier.dart
      mix_generator|dto:
        generate_for:
          - lib/**/shape_border_dto.dart
          
      # mix_generator|enum_utility:
      #   generate_for:
      #     - lib/**/*_util.dart
      # mix_generator|class_utility:
      #   generate_for:
      #     - lib/**/*_util.dart