targets:
  $default:
    builders:
      mix_generator|spec:
        generate_for:
          - lib/**/*_spec.dart
          - lib/**/*_modifier.dart
      mix_generator|dto:
        generate_for:
          - lib/**/*_dto.dart
          
      mix_generator|utility:
        generate_for:
          - lib/**/*_util.dart