targets:
  $default:
    builders:
      mix_generator:
        enabled: true
        generate_for:
          - lib/src/specs/**/*.dart  # Only run on spec files
        options:
          debug: false