import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final outDir = args.isEmpty
      ? Directory('../../.context/tailwinds-spec/out')
      : Directory(args.single);
  if (!outDir.existsSync()) {
    stderr.writeln('Tailwind spec out directory not found: ${outDir.path}');
    exitCode = 64;
    return;
  }

  final classList = (_readJson(outDir, 'class-list.json') as Map)
      .cast<String, Object?>();
  final variants = (_readJson(outDir, 'variants.json') as Map)
      .cast<String, Object?>();
  final probes = (_readJson(outDir, 'candidate-probes.json') as Map)
      .cast<String, Object?>();
  final staticScan = _readJson(outDir, 'static-utilities.scan.json');
  final functionalScan = _readJson(outDir, 'functional-utilities.scan.json');

  final staticUtilityRoots = <String>{
    ..._literalRegistrationNames(staticScan),
    ..._probeRoots(probes, kind: 'static'),
    ..._supportedStaticFallbackRoots(),
  };
  final functionalUtilityRoots = <String>{
    ..._literalRegistrationNames(functionalScan).map(_stripNegativeRoot),
    ..._probeRoots(probes, kind: 'functional'),
    ..._supportedFallbackRoots(classList),
  }..removeWhere((root) => root.isEmpty);

  final staticVariantRoots = <String>{};
  final functionalVariantRoots = <String>{};
  final compoundVariantRoots = <String>{};
  for (final variant in (variants['variants'] as List).cast<Object?>()) {
    final map = (variant as Map).cast<String, Object?>();
    final name = map['name']! as String;
    final values = (map['values'] as List?) ?? const [];
    final isArbitrary = map['isArbitrary'] == true;
    if (name == 'group' || name == 'peer' || name == 'not') {
      compoundVariantRoots.add(name);
    } else if (values.isNotEmpty || isArbitrary || name.startsWith('@')) {
      functionalVariantRoots.add(name);
    } else {
      staticVariantRoots.add(name);
    }
  }
  staticVariantRoots.add('light');

  final meta =
      ((probes['meta'] ?? classList['meta'] ?? variants['meta']) as Map)
          .cast<String, Object?>();
  final generated = DateTime.now().toUtc().toIso8601String();

  final output = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by tool/gen_registry.dart from ${outDir.path}.')
    ..writeln('// Generated at $generated.')
    ..writeln('library;')
    ..writeln()
    ..writeln("import '../parser_registry.dart';")
    ..writeln()
    ..writeln(
      'const generatedTailwindRegistryMeta = <String, Object?>${_dartMap({...meta, 'generatedAt': generated})};',
    )
    ..writeln()
    ..writeln(
      'const generatedStaticUtilityRoots = <String>{${_dartStringSet(staticUtilityRoots)}};',
    )
    ..writeln()
    ..writeln(
      'const generatedFunctionalUtilityRoots = <String>{${_dartStringSet(functionalUtilityRoots)}};',
    )
    ..writeln()
    ..writeln(
      'const generatedStaticVariantRoots = <String>{${_dartStringSet(staticVariantRoots)}};',
    )
    ..writeln()
    ..writeln(
      'const generatedFunctionalVariantRoots = <String>{${_dartStringSet(functionalVariantRoots)}};',
    )
    ..writeln()
    ..writeln(
      'const generatedCompoundVariantRoots = <String>{${_dartStringSet(compoundVariantRoots)}};',
    )
    ..writeln()
    ..writeln('final defaultTailwindParserRegistry = TailwindParserRegistry(')
    ..writeln('  staticUtilityRoots: generatedStaticUtilityRoots,')
    ..writeln('  functionalUtilityRoots: generatedFunctionalUtilityRoots,')
    ..writeln('  staticVariantRoots: generatedStaticVariantRoots,')
    ..writeln('  functionalVariantRoots: generatedFunctionalVariantRoots,')
    ..writeln('  compoundVariantRoots: generatedCompoundVariantRoots,')
    ..writeln('  meta: generatedTailwindRegistryMeta,')
    ..writeln(');');

  final target = File('lib/src/parser/data/parser_registry.g.dart')
    ..parent.createSync(recursive: true);
  target.writeAsStringSync(output.toString());
}

Object? _readJson(Directory dir, String name) {
  final file = File('${dir.path}/$name');
  return jsonDecode(file.readAsStringSync());
}

Iterable<String> _literalRegistrationNames(Object? json) sync* {
  for (final raw in (json as List?) ?? const []) {
    final map = (raw as Map).cast<String, Object?>();
    final name =
        (((map['metaVariables'] as Map?)?['single'] as Map?)?['NAME']
            as Map?)?['text'];
    if (name is! String || name.length < 2) continue;
    final quote = name[0];
    if ((quote == "'" || quote == '"' || quote == '`') &&
        name.endsWith(quote) &&
        !name.contains(r'$')) {
      yield name.substring(1, name.length - 1);
    }
  }
}

Iterable<String> _probeRoots(
  Map<String, Object?> probes, {
  required String kind,
}) sync* {
  for (final raw in (probes['probes'] as List).cast<Object?>()) {
    final map = (raw as Map).cast<String, Object?>();
    if (map['valid'] != true || map['utilityKind'] != kind) continue;
    final root = map['utilityRoot'];
    if (root is String) yield _stripNegativeRoot(root);
  }
}

Iterable<String> _supportedFallbackRoots(Map<String, Object?> classList) {
  final classNames = (classList['classList'] as List)
      .cast<List>()
      .map((row) => _stripNegativeRoot(row.first! as String))
      .toSet();

  const supported = {
    'p',
    'px',
    'py',
    'pt',
    'pr',
    'pb',
    'pl',
    'm',
    'mx',
    'my',
    'mt',
    'mr',
    'mb',
    'ml',
    'w',
    'h',
    'min-w',
    'min-h',
    'max-w',
    'max-h',
    'rounded',
    'rounded-t',
    'rounded-b',
    'rounded-l',
    'rounded-r',
    'rounded-tl',
    'rounded-tr',
    'rounded-bl',
    'rounded-br',
    'border',
    'border-t',
    'border-r',
    'border-b',
    'border-l',
    'border-x',
    'border-y',
    'bg-gradient',
    'from',
    'via',
    'to',
    'translate-x',
    'translate-y',
  };

  const keepEvenWhenMissingFromClassList = {'bg-gradient', 'from', 'via', 'to'};

  return supported.where((root) {
    if (keepEvenWhenMissingFromClassList.contains(root)) return true;
    final prefix = '$root-';
    return classNames.any((name) => name.startsWith(prefix));
  });
}

Iterable<String> _supportedStaticFallbackRoots() {
  return const {'overflow-hidden', 'overflow-visible', 'overflow-clip'};
}

String _stripNegativeRoot(String value) =>
    value.startsWith('-') ? value.substring(1) : value;

String _dartStringSet(Set<String> values) {
  final sorted = values.toList()..sort();
  if (sorted.isEmpty) return '';
  return '\n  ${sorted.map((value) => "'${_escape(value)}'").join(',\n  ')},\n';
}

String _dartMap(Map<String, Object?> values) {
  final entries = values.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));
  return '{\n  ${entries.map((entry) => "'${_escape(entry.key)}': ${_dartValue(entry.value)}").join(',\n  ')},\n}';
}

String _dartValue(Object? value) {
  return switch (value) {
    null => 'null',
    String() => "'${_escape(value)}'",
    num() || bool() => '$value',
    _ => "'${_escape('$value')}'",
  };
}

String _escape(String value) =>
    value.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
