name: mix_lint
description: A linter for the mix package
version: 0.1.0
repository: https://github.com/conceptadev/mix

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  analyzer: ^6.0.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.6.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
