name: example
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.2 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  mix:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
