name: example
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.9.0-196.1.beta <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  mix:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
