import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:mix_schema/mix_schema.dart';

const String _goldenPath = 'test/golden/schema_export_fingerprint.json';

/// Captures the high-signal shape of `exportJsonSchema()` without snapshotting
/// the full recursive expansion (which inflates to ~250k lines because
/// variant→style→variant schemas unfold). The fingerprint covers:
///
/// - Top-level metadata keys.
/// - The set of discriminated branch `type` values (built-in stylers).
/// - The sorted property keys on each branch (field-name drift detection).
/// - The variant-priority metadata leaves the contract advertises.
/// - The total byte length of the canonical JSON output so silent drift
///   in deep nodes still trips the test.
///
/// Intentional drift is regenerated by `UPDATE_GOLDEN=1`.
void main() {
  test('exportJsonSchema() structural fingerprint matches golden', () {
    final schema = MixSchemaContract.builtIn().exportJsonSchema();
    final fingerprint = _fingerprint(schema);
    final actual = '${const JsonEncoder.withIndent('  ').convert(fingerprint)}\n';

    final goldenFile = File(_goldenPath);
    if (Platform.environment['UPDATE_GOLDEN'] == '1' ||
        !goldenFile.existsSync()) {
      goldenFile.parent.createSync(recursive: true);
      goldenFile.writeAsStringSync(actual);
      return;
    }

    expect(
      actual,
      goldenFile.readAsStringSync(),
      reason:
          'exportJsonSchema() fingerprint drifted from $_goldenPath. '
          'If the drift is intentional, regenerate with '
          'UPDATE_GOLDEN=1 flutter test ${_goldenPath.replaceFirst('.json', '_test.dart')}',
    );
  });
}

Map<String, Object?> _fingerprint(Map<String, Object?> schema) {
  final branches = (schema['anyOf'] as List<Object?>?) ?? const <Object?>[];

  return <String, Object?>{
    'topLevelKeys': schema.keys.toList()..sort(),
    'schemaVersion': schema['x-mix-schema-version'],
    'schemaContract': schema['x-mix-schema-contract'],
    'limits': schema['x-mix-schema-limits'],
    'variantPriority': schema['x-mix-variant-priority'],
    'branchTypes': [
      for (final branch in branches)
        if (branch is Map<String, Object?>) _branchType(branch),
    ],
    'branchProperties': {
      for (final branch in branches)
        if (branch is Map<String, Object?> && _branchType(branch) != null)
          _branchType(branch)!: _propertyKeys(branch),
    },
    'fullExportByteLength': utf8.encode(_canonicalJson(schema)).length,
  };
}

String? _branchType(Map<String, Object?> branch) {
  final properties = branch['properties'];
  if (properties is! Map<String, Object?>) return null;
  final typeNode = properties['type'];
  if (typeNode is! Map<String, Object?>) return null;
  final constValue = typeNode['const'];
  return constValue is String ? constValue : null;
}

List<String> _propertyKeys(Map<String, Object?> branch) {
  final properties = branch['properties'];
  if (properties is! Map<String, Object?>) return const <String>[];

  return properties.keys.toList()..sort();
}

/// Stable, canonical JSON representation: keys sorted at every level so the
/// hash is insensitive to map iteration order.
String _canonicalJson(Object? value) {
  return jsonEncode(_canonicalize(value));
}

Object? _canonicalize(Object? value) {
  if (value is Map) {
    final keys = value.keys.cast<String>().toList()..sort();
    return {for (final key in keys) key: _canonicalize(value[key])};
  }
  if (value is List) {
    return [for (final entry in value) _canonicalize(entry)];
  }
  return value;
}
