import 'dart:convert';

import '../json_map.dart';

const _groupOrder = [
  'colors',
  'spaces',
  'doubles',
  'radii',
  'textStyles',
  'shadows',
  'boxShadows',
  'borders',
  'fontWeights',
  'breakpoints',
  'durations',
];

const _tokenClasses = {
  'colors': ('ColorToken', 'color'),
  'spaces': ('SpaceToken', 'space'),
  'doubles': ('DoubleToken', 'double'),
  'radii': ('RadiusToken', 'radius'),
  'textStyles': ('TextStyleToken', 'textStyle'),
  'shadows': ('ShadowToken', 'shadow'),
  'boxShadows': ('BoxShadowToken', 'boxShadow'),
  'borders': ('BorderSideToken', 'border'),
  'fontWeights': ('FontWeightToken', 'fontWeight'),
  'breakpoints': ('BreakpointToken', 'breakpoint'),
  'durations': ('DurationToken', 'duration'),
};

/// Generates standalone Dart token declarations and one scope map per mode.
String generateTokensSource(Map<String, JsonMap> themeDocuments) {
  if (themeDocuments.isEmpty) {
    throw ArgumentError.value(
      themeDocuments,
      'themeDocuments',
      'Must not be empty.',
    );
  }
  final declarations = <(String, String)>{};
  for (final theme in themeDocuments.values) {
    _validateTheme(theme);
    for (final group in _groupOrder) {
      final values = _group(theme, group);
      for (final name in values.keys) {
        declarations.add((group, name));
      }
    }
  }
  final orderedDeclarations = declarations.toList()
    ..sort((left, right) {
      final groupCompare = _groupOrder
          .indexOf(left.$1)
          .compareTo(_groupOrder.indexOf(right.$1));

      return groupCompare != 0 ? groupCompare : left.$2.compareTo(right.$2);
    });
  _validateUniqueTokenIdentifiers(orderedDeclarations);

  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by package:mix_figma.')
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln("import 'package:mix/mix.dart';")
    ..writeln();
  for (final (group, name) in orderedDeclarations) {
    final token = _tokenClasses[group]!;
    buffer.writeln(
      'const ${_identifier(token.$2, name)} = '
      "${token.$1}(${jsonEncode(name)});",
    );
  }

  final modes = themeDocuments.keys.toList()..sort();
  _validateUniqueModeIdentifiers(modes);
  for (final mode in modes) {
    final theme = themeDocuments[mode]!;
    buffer
      ..writeln()
      ..writeln('final ${_dartIdentifier(mode)}Tokens = <MixToken, Object>{');
    for (final group in _groupOrder) {
      final values = _group(theme, group);
      final names = values.keys.toList()..sort();
      for (final name in names) {
        final token = _tokenClasses[group]!;
        final resolved = _resolveAlias(values, name, active: {});
        buffer.writeln(
          '  ${_identifier(token.$2, name)}: '
          '${_dartValue(group, resolved)},',
        );
      }
    }
    buffer.writeln('};');
  }

  return buffer.toString();
}

void _validateUniqueModeIdentifiers(List<String> modes) {
  final namesByIdentifier = <String, String>{};
  for (final mode in modes) {
    final identifier = _dartIdentifier(mode);
    final existing = namesByIdentifier[identifier];
    if (existing != null && existing != mode) {
      throw FormatException(
        'Mode names "$existing" and "$mode" both normalize to the Dart '
        'identifier "${identifier}Tokens".',
      );
    }
    namesByIdentifier[identifier] = mode;
  }
}

void _validateUniqueTokenIdentifiers(List<(String, String)> declarations) {
  final namesByIdentifier = <String, String>{};
  for (final (group, name) in declarations) {
    final identifier = _identifier(_tokenClasses[group]!.$2, name);
    final existing = namesByIdentifier[identifier];
    if (existing != null && existing != name) {
      throw FormatException(
        'Token names "$existing" and "$name" both normalize to the Dart '
        'identifier "$identifier".',
      );
    }
    namesByIdentifier[identifier] = name;
  }
}

void _validateTheme(JsonMap theme) {
  if (theme['v'] != 1 || theme['type'] != 'theme') {
    throw const FormatException('Expected a v1 Mix protocol theme document.');
  }
}

JsonMap _group(JsonMap theme, String group) {
  final value = theme[group];
  if (value == null) return {};
  if (value is! Map) throw FormatException('Theme group $group must be a map.');

  return value.cast();
}

Object? _resolveAlias(
  JsonMap values,
  String name, {
  required Set<String> active,
}) {
  if (!active.add(name)) throw FormatException('Alias cycle at $name.');
  final value = values[name];
  if (value is Map && value[r'$token'] is String) {
    final target = value[r'$token']! as String;
    if (!values.containsKey(target)) {
      throw FormatException('Alias target $target does not exist.');
    }

    return _resolveAlias(values, target, active: active);
  }

  return value;
}

String _identifier(String prefix, String name) {
  final words = name
      .split(RegExp(r'[^A-Za-z0-9]+'))
      .where((word) => word.isNotEmpty);

  return '$prefix${words.map(_upperFirst).join()}';
}

String _dartIdentifier(String value) {
  final words = value
      .split(RegExp(r'[^A-Za-z0-9]+'))
      .where((word) => word.isNotEmpty)
      .toList();
  if (words.isEmpty) return 'mode';
  final result =
      '${words.first.toLowerCase()}${words.skip(1).map(_upperFirst).join()}';

  return RegExp(r'^[0-9]').hasMatch(result) ? 'mode$result' : result;
}

String _upperFirst(String word) =>
    '${word.substring(0, 1).toUpperCase()}${word.substring(1)}';

String _dartValue(String group, Object? value) {
  return switch (group) {
    'colors' => 'const Color(${_colorValue(value)})',
    'spaces' || 'doubles' => _double(value),
    'radii' => _radius(value),
    'textStyles' => _textStyle(value),
    'shadows' => _shadowList(value, box: false),
    'boxShadows' => _shadowList(value, box: true),
    'borders' => _border(value),
    'fontWeights' => 'FontWeight.${value! as String}',
    'breakpoints' => _breakpoint(value),
    'durations' => 'const Duration(milliseconds: ${value! as num})',
    _ => throw FormatException('Unsupported group $group.'),
  };
}

String _colorValue(Object? value) {
  if (value is! String) throw const FormatException('Expected color string.');
  final hex = value.substring(1).toUpperCase();

  return '0x${hex.length == 6 ? 'FF$hex' : hex}';
}

String _double(Object? value) {
  if (value is! num || !value.isFinite) {
    throw const FormatException('Expected finite number.');
  }

  return value.toDouble().toString();
}

String _radius(Object? value) {
  if (value is num) return 'Radius.circular(${_double(value)})';
  final radius = value is Map ? value.cast<String, Object?>() : null;
  if (radius != null && radius['x'] is num && radius['y'] is num) {
    return 'Radius.elliptical(${_double(radius['x'])}, ${_double(radius['y'])})';
  }
  throw const FormatException('Expected radius number or x/y object.');
}

String _textStyle(Object? value) {
  final style = value is Map ? value.cast<String, Object?>() : null;
  if (style == null) throw const FormatException('Expected text style object.');
  final arguments = <String>[];
  if (style['color'] != null) {
    arguments.add('color: const Color(${_colorValue(style['color'])})');
  }
  if (style['backgroundColor'] != null) {
    arguments.add(
      'backgroundColor: const Color(${_colorValue(style['backgroundColor'])})',
    );
  }
  for (final key in ['fontSize', 'letterSpacing', 'wordSpacing', 'height']) {
    if (style[key] != null) arguments.add('$key: ${_double(style[key])}');
  }
  if (style['fontWeight'] case final String fontWeight) {
    arguments.add('fontWeight: FontWeight.$fontWeight');
  }
  if (style['fontStyle'] case final String fontStyle) {
    arguments.add('fontStyle: FontStyle.$fontStyle');
  }
  if (style['fontFamily'] != null) {
    arguments.add('fontFamily: ${jsonEncode(style['fontFamily'])}');
  }

  return 'TextStyle(${arguments.join(', ')})';
}

String _shadowList(Object? value, {required bool box}) {
  if (value is! List) throw const FormatException('Expected shadow list.');
  final className = box ? 'BoxShadow' : 'Shadow';
  final values = value
      .map((item) {
        final shadow = (item! as Map).cast<String, Object?>();
        final offset = (shadow['offset']! as Map).cast<String, Object?>();

        return '$className('
            'color: const Color(${_colorValue(shadow['color'])}), '
            'offset: Offset(${_double(offset['x'])}, ${_double(offset['y'])}), '
            'blurRadius: ${_double(shadow['blurRadius'])}'
            '${box && shadow['spreadRadius'] != null ? ', spreadRadius: ${_double(shadow['spreadRadius'])}' : ''}'
            ')';
      })
      .join(', ');

  return '<$className>[$values]';
}

String _border(Object? value) {
  final border = (value! as Map).cast<String, Object?>();
  final style = border['style'];
  if (style is! String) throw const FormatException('Expected border style.');

  return 'BorderSide('
      'color: const Color(${_colorValue(border['color'])}), '
      'width: ${_double(border['width'])}, '
      'style: BorderStyle.$style'
      ')';
}

String _breakpoint(Object? value) {
  final breakpoint = (value! as Map).cast<String, Object?>();
  if (breakpoint['minWidth'] != null && breakpoint.length == 1) {
    return 'Breakpoint.minWidth(${_double(breakpoint['minWidth'])})';
  }
  if (breakpoint['maxWidth'] != null && breakpoint.length == 1) {
    return 'Breakpoint.maxWidth(${_double(breakpoint['maxWidth'])})';
  }
  throw const FormatException('Breakpoint must contain one min/max width.');
}
