include: ../packages/mix/analysis_options.yaml

analyzer:
  errors:
    prefer_const_constructors: ignore
  enable-experiment:
    - dot-shorthands

linter:
  rules:
    use_build_context_synchronously: false
