include: ../packages/mix/analysis_options.yaml

analyzer:
  exclude:
    - build/**
  errors:
    prefer_const_constructors: ignore
  enable-experiment:
    - dot-shorthands
    
plugins:
  mix_lint:
    path: ../packages/mix_lint
    diagnostics:
      mix_avoid_defining_tokens_within_style: true
      mix_avoid_defining_tokens_within_scope: true
      mix_avoid_empty_variants: true
      mix_max_number_of_attributes_per_style: true
      mix_prefer_dot_shorthands: true
      mix_variants_last: true
      mix_mixable_styler_has_create: true
