///   /\\\\            /\\\\  /\\\\\\\\\\\  /\\\       /\\\
///   \/\\\\\\        /\\\\\\ \/////\\\///  \///\\\   /\\\/
///    \/\\\//\\\    /\\\//\\\     \/\\\       \///\\\\\\/
///     \/\\\\///\\\/\\\/ \/\\\     \/\\\         \//\\\\
///      \/\\\  \///\\\/   \/\\\     \/\\\          \/\\\\
///       \/\\\    \///     \/\\\     \/\\\          /\\\\\\
///        \/\\\             \/\\\     \/\\\        /\\\////\\\
///         \/\\\             \/\\\  /\\\\\\\\\\\  /\\\/   \///\\\
///          \///              \///  \///////////  \///       \///
///
///                        https://fluttermix.com
///
///             /\///////////////////////////////////////////////////\
///             \/\           ***** GENERATED CODE *****            \ \
///              \/\            ** DO NOT EDIT THIS FILE **          \ \
///               \/\             Generated with barrel script        \ \
///                \/////////////////////////////////////////////////////

library mix;

/// ATTRIBUTES
export 'src/attributes/animation/animation_config.dart';
export 'src/attributes/border/border_dto.dart';
export 'src/attributes/border/border_radius_dto.dart';
export 'src/attributes/border/border_radius_util.dart';
export 'src/attributes/border/border_util.dart';
export 'src/attributes/border/shape_border_dto.dart';
export 'src/attributes/border/shape_border_util.dart';
export 'src/attributes/color/color_extensions.dart';
export 'src/attributes/color/color_util.dart';
export 'src/attributes/color/material_colors_util.dart';
export 'src/attributes/constraints/constraints_dto.dart';
export 'src/attributes/constraints/constraints_util.dart';
export 'src/attributes/decoration/decoration_dto.dart';
export 'src/attributes/decoration/decoration_util.dart';
export 'src/attributes/decoration/image/decoration_image_dto.dart';
export 'src/attributes/decoration/image/decoration_image_util.dart';
export 'src/attributes/enum/enum_util.dart';
export 'src/attributes/gap/gap_util.dart';
export 'src/attributes/gap/space_dto.dart';
export 'src/attributes/gradient/gradient_dto.dart';
export 'src/attributes/gradient/gradient_util.dart';
export 'src/attributes/scalars/curves.dart';
export 'src/attributes/scalars/scalar_util.dart';
export 'src/attributes/shadow/shadow_dto.dart';
export 'src/attributes/shadow/shadow_util.dart';
export 'src/attributes/spacing/edge_insets_dto.dart';
export 'src/attributes/spacing/spacing_util.dart';
export 'src/attributes/strut_style/strut_style_dto.dart';
export 'src/attributes/strut_style/strut_style_util.dart';
export 'src/attributes/text_height_behavior/text_height_behavior_dto.dart';
export 'src/attributes/text_height_behavior/text_height_behavior_util.dart';
export 'src/attributes/text_style/text_style_dto.dart';
export 'src/attributes/text_style/text_style_util.dart';
export 'src/core/animation/animation_driver.dart';
export 'src/core/animation/controlled_animation_driver.dart';
export 'src/core/animation/phase_animation_driver.dart';
export 'src/core/attribute.dart';
export 'src/core/deprecated.dart';
export 'src/core/directive.dart';
export 'src/core/factory/style_mix.dart';
export 'src/core/helpers.dart';

/// CORE
export 'src/core/mix_element.dart';
export 'src/core/modifier.dart';
export 'src/core/named_variant_scope.dart';
export 'src/core/prop.dart';
export 'src/core/resolved_style_provider.dart';
export 'src/core/spec.dart';
export 'src/core/style_builder.dart';
export 'src/core/style_provider.dart';
export 'src/core/styled_widget.dart';
export 'src/core/utility.dart';
export 'src/core/variant.dart';
export 'src/core/widget_state/widget_state_controller.dart';
export 'src/helpers/duration.dart';

/// MODIFIERS
export 'src/modifiers/align_widget_modifier.dart';
export 'src/modifiers/aspect_ratio_widget_modifier.dart';
export 'src/modifiers/clip_widget_modifier.dart';
export 'src/modifiers/flexible_widget_modifier.dart';
export 'src/modifiers/fractionally_sized_box_widget_modifier.dart';
export 'src/modifiers/intrinsic_widget_modifier.dart';
export 'src/modifiers/mouse_cursor_modifier.dart';
export 'src/modifiers/opacity_widget_modifier.dart';
export 'src/modifiers/padding_widget_modifier.dart';
export 'src/modifiers/rotated_box_widget_modifier.dart';
export 'src/modifiers/scroll_view_widget_modifier.dart';
export 'src/modifiers/sized_box_widget_modifier.dart';
export 'src/modifiers/transform_widget_modifier.dart';
export 'src/modifiers/visibility_widget_modifier.dart';
export 'src/modifiers/widget_modifiers_util.dart';

/// SPECS
export 'src/specs/box/box_spec.dart';
export 'src/specs/box/box_widget.dart';
export 'src/specs/flex/flex_spec.dart';
export 'src/specs/flexbox/flexbox_spec.dart';
export 'src/specs/flexbox/flexbox_widget.dart';
export 'src/specs/icon/icon_spec.dart';
export 'src/specs/icon/icon_widget.dart';
export 'src/specs/image/image_spec.dart';
export 'src/specs/image/image_widget.dart';
export 'src/specs/spec_util.dart';
export 'src/specs/stack/stack_box_spec.dart';
export 'src/specs/stack/stack_box_style.dart';
export 'src/specs/stack/stack_spec.dart';
export 'src/specs/stack/stack_widget.dart';
export 'src/specs/text/text_directives_util.dart';
export 'src/specs/text/text_spec.dart';
export 'src/specs/text/text_widget.dart';

/// THEME
export 'src/theme/material/material_theme.dart';
export 'src/theme/material/material_tokens.dart';
export 'src/theme/mix/mix_theme.dart';
export 'src/theme/tokens/mix_token.dart';
export 'src/theme/tokens/value_resolver.dart';

/// WIDGETS
export 'src/widgets/pressable_widget.dart';
