///   /\\\\            /\\\\  /\\\\\\\\\\\  /\\\       /\\\
///   \/\\\\\\        /\\\\\\ \/////\\\///  \///\\\   /\\\/
///    \/\\\//\\\    /\\\//\\\     \/\\\       \///\\\\\\/
///     \/\\\\///\\\/\\\/ \/\\\     \/\\\         \//\\\\
///      \/\\\  \///\\\/   \/\\\     \/\\\          \/\\\\
///       \/\\\    \///     \/\\\     \/\\\          /\\\\\\
///        \/\\\             \/\\\     \/\\\        /\\\////\\\
///         \/\\\             \/\\\  /\\\\\\\\\\\  /\\\/   \///\\\
///          \///              \///  \///////////  \///       \///
///
///                        https://fluttermix.com
///
///             /\///////////////////////////////////////////////////\
///             \/\           ***** GENERATED CODE *****            \ \
///              \/\            ** DO NOT EDIT THIS FILE **          \ \
///               \/\             Generated with barrel script        \ \
///                \/////////////////////////////////////////////////////

library;

/// ANIMATION
export 'src/animation/animation_config.dart';
export 'src/animation/animation_util.dart';
export 'src/animation/curves.dart';
export 'src/animation/style_animation_builder.dart';
export 'src/animation/style_animation_driver.dart';

/// CORE
export 'src/core/breakpoint.dart';
export 'src/core/cursor_position.dart';
export 'src/core/extensions/extensions.dart';
export 'src/core/helpers.dart';
export 'src/core/mix_element.dart';
export 'src/core/modifier.dart';
export 'src/core/prop.dart';
export 'src/core/prop_refs.dart';
export 'src/core/prop_source.dart';
export 'src/core/providers/resolved_style_provider.dart';
export 'src/core/providers/style_provider.dart';
export 'src/core/providers/widget_state_provider.dart';
export 'src/core/spec.dart';
export 'src/core/spec_utility.dart';
export 'src/core/style.dart' hide StyleElement;
export 'src/core/style_builder.dart';
export 'src/core/style_widget.dart';
export 'src/core/utility.dart';
export 'src/core/widget_decorator.dart';
export 'src/decorators/align_decorator.dart';
export 'src/decorators/aspect_ratio_decorator.dart';
export 'src/decorators/clip_decorator.dart';
export 'src/decorators/default_text_style_decorator.dart';
export 'src/decorators/flexible_decorator.dart';
export 'src/decorators/fractionally_sized_box_decorator.dart';
export 'src/decorators/icon_theme_decorator.dart';
export 'src/decorators/intrinsic_decorator.dart';
export 'src/decorators/mouse_cursor_decorator.dart';
export 'src/decorators/opacity_decorator.dart';
export 'src/decorators/padding_decorator.dart';
export 'src/decorators/rotated_box_decorator.dart';
export 'src/decorators/scroll_view_decorator.dart';
export 'src/decorators/sized_box_decorator.dart';
export 'src/decorators/transform_decorator.dart';
export 'src/decorators/visibility_decorator.dart';

/// WIDGET DECORATORS
export 'src/decorators/widget_decorator_config.dart';
export 'src/decorators/widget_decorator_util.dart';

/// PROPERTIES
export 'src/properties/layout/constraints_mix.dart';
export 'src/properties/layout/constraints_util.dart';
export 'src/properties/layout/edge_insets_geometry_mix.dart';
export 'src/properties/layout/edge_insets_geometry_util.dart'
    hide createEdgeInsetsMix;
export 'src/properties/layout/enum_util.dart';
export 'src/properties/layout/scalar_util.dart';
export 'src/properties/painting/border_mix.dart';
export 'src/properties/painting/border_radius_mix.dart';
export 'src/properties/painting/border_radius_util.dart';
export 'src/properties/painting/border_util.dart';
export 'src/properties/painting/color_mix.dart';
export 'src/properties/painting/color_util.dart';
export 'src/properties/painting/decoration_image_mix.dart';
export 'src/properties/painting/decoration_image_util.dart';
export 'src/properties/painting/decoration_mix.dart';
export 'src/properties/painting/decoration_util.dart';
export 'src/properties/painting/gradient_mix.dart';
export 'src/properties/painting/gradient_util.dart';
export 'src/properties/painting/material_colors_util.dart';
export 'src/properties/painting/shadow_mix.dart';
export 'src/properties/painting/shadow_util.dart';
export 'src/properties/painting/shape_border_mix.dart';
export 'src/properties/painting/shape_border_util.dart';
export 'src/properties/typography/strut_style_mix.dart';
export 'src/properties/typography/strut_style_util.dart';
export 'src/properties/typography/text_height_behavior_mix.dart';
export 'src/properties/typography/text_height_behavior_util.dart';
export 'src/properties/typography/text_style_mix.dart';
export 'src/properties/typography/text_style_util.dart';

/// SPECS
export 'src/specs/box/box_attribute.dart';
export 'src/specs/box/box_spec.dart';
export 'src/specs/box/box_util.dart';
export 'src/specs/box/box_widget.dart';
export 'src/specs/flex/flex_attribute.dart';
export 'src/specs/flex/flex_spec.dart';
export 'src/specs/flex/flex_util.dart';
export 'src/specs/flexbox/flexbox_attribute.dart';
export 'src/specs/flexbox/flexbox_spec.dart';
export 'src/specs/flexbox/flexbox_util.dart';
export 'src/specs/flexbox/flexbox_widget.dart';
export 'src/specs/icon/icon_attribute.dart';
export 'src/specs/icon/icon_spec.dart';
export 'src/specs/icon/icon_util.dart';
export 'src/specs/icon/icon_widget.dart';
export 'src/specs/image/image_attribute.dart';
export 'src/specs/image/image_spec.dart';
export 'src/specs/image/image_util.dart';
export 'src/specs/image/image_widget.dart';
export 'src/specs/pressable/pressable_widget.dart';
export 'src/specs/spec_util.dart';
export 'src/specs/stack/stack_attribute.dart';
export 'src/specs/stack/stack_box_attribute.dart';
export 'src/specs/stack/stack_box_spec.dart';
export 'src/specs/stack/stack_spec.dart';
export 'src/specs/stack/stack_util.dart';
export 'src/specs/stack/stack_widget.dart';
export 'src/specs/text/text_attribute.dart';
export 'src/specs/text/text_spec.dart';
export 'src/specs/text/text_util.dart';
export 'src/specs/text/text_widget.dart';

/// THEME
export 'src/theme/material/material_theme.dart';
export 'src/theme/material/material_tokens.dart';
export 'src/theme/mix_theme.dart';
export 'src/theme/tokens/mix_token.dart';

/// VARIANTS
export 'src/variants/variant.dart';
export 'src/variants/variant_util.dart';
