#!/bin/bash

# SessionStart hook to set up Flutter/FVM/Melos environment
# This runs automatically when Claude Code web sessions start

# Only run in Claude Code remote/web sessions
if [ "$CLAUDE_CODE_REMOTE" != "true" ]; then
  exit 0
fi

# Run the setup script if tools aren't installed yet
if [ ! -x "$HOME/fvm/bin/fvm" ] || [ ! -d "$CLAUDE_PROJECT_DIR/.fvm/flutter_sdk" ]; then
  if [ -x "$CLAUDE_PROJECT_DIR/setup.sh" ]; then
    cd "$CLAUDE_PROJECT_DIR" && ./setup.sh
  fi
fi

# Generate .flutter_env if it doesn't exist
if [ ! -f "$CLAUDE_PROJECT_DIR/.flutter_env" ]; then
  FVM_BIN_DIR="$HOME/fvm/bin"
  PUB_CACHE_BIN="$HOME/.pub-cache/bin"
  FLUTTER_SDK_BIN="$CLAUDE_PROJECT_DIR/.fvm/flutter_sdk/bin"

  {
    echo "# Auto-generated by setup-flutter-env.sh"
    echo "export PATH=\"$FVM_BIN_DIR:$PUB_CACHE_BIN:\$PATH\""
    if [ -d "$FLUTTER_SDK_BIN" ]; then
      echo "export PATH=\"$FLUTTER_SDK_BIN:\$PATH\""
    fi
  } > "$CLAUDE_PROJECT_DIR/.flutter_env"
fi

# Persist environment variables for the session
if [ -n "$CLAUDE_ENV_FILE" ] && [ -f "$CLAUDE_PROJECT_DIR/.flutter_env" ]; then
  cat "$CLAUDE_PROJECT_DIR/.flutter_env" >> "$CLAUDE_ENV_FILE"
fi

exit 0
