#!/bin/bash
set -euo pipefail

# SessionStart hook to set up Flutter/FVM/Melos environment
# This runs automatically when Claude Code web sessions start

# Only run in Claude Code remote/web sessions
if [ "$CLAUDE_CODE_REMOTE" != "true" ]; then
  exit 0
fi

# Defensive check: ensure CLAUDE_PROJECT_DIR is set
if [ -z "${CLAUDE_PROJECT_DIR:-}" ]; then
  echo "ERROR: CLAUDE_PROJECT_DIR is not set" >&2
  exit 2
fi

# Change to project directory immediately to avoid path issues
cd "$CLAUDE_PROJECT_DIR" || exit 2

# Run the setup script if tools aren't installed yet
if [ ! -x "$HOME/fvm/bin/fvm" ] || [ ! -d ".fvm/flutter_sdk" ]; then
  if [ -x "./setup.sh" ]; then
    ./setup.sh
  fi
fi

# Generate .flutter_env if it doesn't exist
if [ ! -f ".flutter_env" ]; then
  FVM_BIN_DIR="$HOME/fvm/bin"
  PUB_CACHE_BIN="$HOME/.pub-cache/bin"
  FLUTTER_SDK_BIN="$PWD/.fvm/flutter_sdk/bin"

  {
    echo "# Auto-generated by setup-flutter-env.sh"
    echo "export PATH=\"$FVM_BIN_DIR:$PUB_CACHE_BIN:\$PATH\""
    if [ -d "$FLUTTER_SDK_BIN" ]; then
      echo "export PATH=\"$FLUTTER_SDK_BIN:\$PATH\""
    fi
  } > ".flutter_env"
fi

# Persist environment variables for the session
if [ -n "${CLAUDE_ENV_FILE:-}" ] && [ -f ".flutter_env" ]; then
  cat ".flutter_env" >> "$CLAUDE_ENV_FILE"
fi

exit 0
