// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by package:mix_figma.

import 'package:flutter/widgets.dart';
import 'package:mix/mix.dart';

const colorColorAccent = ColorToken("color.accent");
const colorColorBrand = ColorToken("color.brand");
const spaceSpaceSm = SpaceToken("space.sm");
const durationDurationFast = DurationToken("duration.fast");

final darkTokens = <MixToken, Object>{
  colorColorAccent: const Color(0xFF8DA4EF),
  colorColorBrand: const Color(0xFF8DA4EF),
  spaceSpaceSm: 8.0,
  durationDurationFast: const Duration(milliseconds: 120),
};

final lightTokens = <MixToken, Object>{
  colorColorAccent: const Color(0xFF336699),
  colorColorBrand: const Color(0xFF336699),
  spaceSpaceSm: 8.0,
  durationDurationFast: const Duration(milliseconds: 120),
};
