targets:
  $default:
    builders:
      mix_generator|spec:
        generate_for:
          - lib/components/**/*.dart
      mix_generator|dto:
        generate_for:
          - lib/components/**/*.dart