targets:
  $default:
    builders:
      mix_generator:
        enabled: true
        generate_for:
          - lib/**/*.dart
        options:
          debug: false

builders:
  mix_generator:
    import: 'package:mix_generator/mix_generator.dart'
    builder_factories: ['mixGenerator']
    build_extensions: {'.dart': ['.mix.dart']}
    auto_apply: dependents
    build_to: source
    applies_builders: []