targets:
  $default:
    builders:
      mix_generator:
        enabled: true
        generate_for:
          - lib/**/*.dart
        options:
          debug: false

builders:
  mix_generator:
    import: 'package:mix_generator/mix_generator.dart'
    builder_factories: ['mixGenerator']
    build_extensions: {'.dart': ['.g.part']}
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
