// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by package:mix_figma.

import 'package:flutter/widgets.dart';
import 'package:mix/mix.dart';

const colorColorBrandAccent = ColorToken("color.brand.accent");
const colorColorBrandPrimary = ColorToken("color.brand.primary");
const spaceSpaceStackSm = SpaceToken("space.stack.sm");
const doubleOpacityDisabled = DoubleToken("opacity.disabled");
const radiusRadiusCard = RadiusToken("radius.card");
const textStyleTypeBody = TextStyleToken("type.body");
const shadowShadowTextSoft = ShadowToken("shadow.text.soft");
const boxShadowShadowTextBox = BoxShadowToken("shadow.text.box");
const borderBorderFocus = BorderSideToken("border.focus");
const fontWeightWeightStrong = FontWeightToken("weight.strong");
const breakpointBreakpointSidebar = BreakpointToken("breakpoint.sidebar");
const durationDurationFast = DurationToken("duration.fast");

final darkTokens = <MixToken, Object>{
  colorColorBrandAccent: const Color(0xFF8DA4EF),
  colorColorBrandPrimary: const Color(0xFF8DA4EF),
  spaceSpaceStackSm: 8.0,
  doubleOpacityDisabled: 0.64,
  radiusRadiusCard: Radius.circular(12.0),
  textStyleTypeBody: TextStyle(fontSize: 14.0, height: 1.4, fontWeight: FontWeight.w400, fontFamily: "Inter"),
  shadowShadowTextSoft: <Shadow>[Shadow(color: const Color(0x33000000), offset: Offset(0.0, 1.0), blurRadius: 2.0)],
  boxShadowShadowTextBox: <BoxShadow>[BoxShadow(color: const Color(0x33000000), offset: Offset(0.0, 2.0), blurRadius: 8.0, spreadRadius: 1.0)],
  borderBorderFocus: BorderSide(color: const Color(0xFF008577), width: 2.0, style: BorderStyle.solid),
  fontWeightWeightStrong: FontWeight.w700,
  breakpointBreakpointSidebar: Breakpoint.minWidth(960.0),
  durationDurationFast: const Duration(milliseconds: 120),
};

final lightTokens = <MixToken, Object>{
  colorColorBrandAccent: const Color(0xFF336699),
  colorColorBrandPrimary: const Color(0xFF336699),
  spaceSpaceStackSm: 8.0,
  doubleOpacityDisabled: 0.64,
  radiusRadiusCard: Radius.circular(12.0),
  textStyleTypeBody: TextStyle(fontSize: 14.0, height: 1.4, fontWeight: FontWeight.w400, fontFamily: "Inter"),
  shadowShadowTextSoft: <Shadow>[Shadow(color: const Color(0x33000000), offset: Offset(0.0, 1.0), blurRadius: 2.0)],
  boxShadowShadowTextBox: <BoxShadow>[BoxShadow(color: const Color(0x33000000), offset: Offset(0.0, 2.0), blurRadius: 8.0, spreadRadius: 1.0)],
  borderBorderFocus: BorderSide(color: const Color(0xFF008577), width: 2.0, style: BorderStyle.solid),
  fontWeightWeightStrong: FontWeight.w700,
  breakpointBreakpointSidebar: Breakpoint.minWidth(960.0),
  durationDurationFast: const Duration(milliseconds: 120),
};
