name: demo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mix:
    path: ../

  cupertino_icons: ^1.0.5
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2

  adaptive_navigation: ^0.0.7
  google_fonts: ^3.0.1
  desktop_window: ^0.4.0
  community_material_icon: ^5.9.55

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.21.2
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.11

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
