#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Find the absolute path to the fvm command
FVM_PATH=$(command -v fvm)

# Check if fvm command is found
if [ -n "$FVM_PATH" ]; then
  # Add the directory containing the fvm command to PATH
  export PATH="$(dirname "$FVM_PATH"):$PATH"
else
  echo "FVM not found. Please make sure it is installed and accessible."
  exit 1
fi

echo "🔧 Formatting and fixing staged Dart files..."
dart run lint_staged

echo "✅ Pre-commit completed!"


