/// Explicit coverage decisions for the `mix_schema` inventory ratchet.
///
/// The inventory checker compares this table against the surface discovered in
/// `packages/mix` at HEAD. Keep ids sorted within each group when editing.
enum SchemaInventoryStatus {
  /// `mix_schema` has a codec for the inventory id.
  supported,

  /// The inventory id is deliberately not represented by the wire contract.
  knownUnsupported,
}

/// One inventory coverage decision.
final class SchemaInventoryEntry {
  const SchemaInventoryEntry._({
    required this.id,
    required this.status,
    this.since,
    this.reason,
  });

  /// Marks [id] as represented by the schema contract.
  const SchemaInventoryEntry.supported(String id, {int since = 1})
    : this._(id: id, status: SchemaInventoryStatus.supported, since: since);

  /// Marks [id] as deliberately unsupported by the schema contract.
  const SchemaInventoryEntry.knownUnsupported(String id, String reason)
    : this._(
        id: id,
        status: SchemaInventoryStatus.knownUnsupported,
        reason: reason,
      );

  /// Stable inventory id.
  final String id;

  /// Coverage decision bucket.
  final SchemaInventoryStatus status;

  /// Wire format version where support first appeared.
  final int? since;

  /// Human-readable reason for known unsupported ids.
  final String? reason;
}

const _phase3Tokens = 'deferred: phase 3 - canonical token wire grammar.';
const _phase4Coverage = 'deferred: phase 4 - codec coverage backlog.';
const _phase4Directives = 'deferred: phase 4 - Prop directive grammar.';
const _phase4Modifiers = 'deferred: phase 4 - modifier codec expansion.';
const _phase4Variants = 'deferred: phase 4 - context variant codec expansion.';
const _neverClosureBacked = 'never: closure-backed runtime behavior.';
const _neverRuntimeOnly = 'never: runtime-only value with no stable data wire.';
const _neverInternal =
    'never: internal or merge-control implementation detail.';

/// Coverage decisions for the current checked-in `packages/mix` inventory.
const schemaInventoryManifest = <SchemaInventoryEntry>[
  ..._supportedInventory,
  ..._phase3DeferredInventory,
  ..._phase4DeferredInventory,
  ..._neverUnsupportedInventory,
];

const _supportedInventory = <SchemaInventoryEntry>[
  SchemaInventoryEntry.supported(r'BoxStyler.$alignment'),
  SchemaInventoryEntry.supported(r'BoxStyler.$animation'),
  SchemaInventoryEntry.supported(r'BoxStyler.$clipBehavior'),
  SchemaInventoryEntry.supported(r'BoxStyler.$constraints'),
  SchemaInventoryEntry.supported(r'BoxStyler.$decoration'),
  SchemaInventoryEntry.supported(r'BoxStyler.$margin'),
  SchemaInventoryEntry.supported(r'BoxStyler.$modifier'),
  SchemaInventoryEntry.supported(r'BoxStyler.$padding'),
  SchemaInventoryEntry.supported(r'BoxStyler.$transform'),
  SchemaInventoryEntry.supported(r'BoxStyler.$transformAlignment'),
  SchemaInventoryEntry.supported(r'BoxStyler.$variants'),
  SchemaInventoryEntry.supported(r'FlexBoxStyler.$animation'),
  SchemaInventoryEntry.supported(r'FlexBoxStyler.$box'),
  SchemaInventoryEntry.supported(r'FlexBoxStyler.$flex'),
  SchemaInventoryEntry.supported(r'FlexBoxStyler.$modifier'),
  SchemaInventoryEntry.supported(r'FlexBoxStyler.$variants'),
  SchemaInventoryEntry.supported(r'FlexStyler.$animation'),
  SchemaInventoryEntry.supported(r'FlexStyler.$clipBehavior'),
  SchemaInventoryEntry.supported(r'FlexStyler.$crossAxisAlignment'),
  SchemaInventoryEntry.supported(r'FlexStyler.$direction'),
  SchemaInventoryEntry.supported(r'FlexStyler.$mainAxisAlignment'),
  SchemaInventoryEntry.supported(r'FlexStyler.$mainAxisSize'),
  SchemaInventoryEntry.supported(r'FlexStyler.$modifier'),
  SchemaInventoryEntry.supported(r'FlexStyler.$spacing'),
  SchemaInventoryEntry.supported(r'FlexStyler.$textBaseline'),
  SchemaInventoryEntry.supported(r'FlexStyler.$textDirection'),
  SchemaInventoryEntry.supported(r'FlexStyler.$variants'),
  SchemaInventoryEntry.supported(r'FlexStyler.$verticalDirection'),
  SchemaInventoryEntry.supported(r'IconStyler.$animation'),
  SchemaInventoryEntry.supported(r'IconStyler.$applyTextScaling'),
  SchemaInventoryEntry.supported(r'IconStyler.$blendMode'),
  SchemaInventoryEntry.supported(r'IconStyler.$color'),
  SchemaInventoryEntry.supported(r'IconStyler.$fill'),
  SchemaInventoryEntry.supported(r'IconStyler.$grade'),
  SchemaInventoryEntry.supported(r'IconStyler.$icon'),
  SchemaInventoryEntry.supported(r'IconStyler.$modifier'),
  SchemaInventoryEntry.supported(r'IconStyler.$opacity'),
  SchemaInventoryEntry.supported(r'IconStyler.$opticalSize'),
  SchemaInventoryEntry.supported(r'IconStyler.$semanticsLabel'),
  SchemaInventoryEntry.supported(r'IconStyler.$size'),
  SchemaInventoryEntry.supported(r'IconStyler.$textDirection'),
  SchemaInventoryEntry.supported(r'IconStyler.$variants'),
  SchemaInventoryEntry.supported(r'IconStyler.$weight'),
  SchemaInventoryEntry.supported(r'ImageStyler.$alignment'),
  SchemaInventoryEntry.supported(r'ImageStyler.$animation'),
  SchemaInventoryEntry.supported(r'ImageStyler.$color'),
  SchemaInventoryEntry.supported(r'ImageStyler.$colorBlendMode'),
  SchemaInventoryEntry.supported(r'ImageStyler.$excludeFromSemantics'),
  SchemaInventoryEntry.supported(r'ImageStyler.$filterQuality'),
  SchemaInventoryEntry.supported(r'ImageStyler.$fit'),
  SchemaInventoryEntry.supported(r'ImageStyler.$gaplessPlayback'),
  SchemaInventoryEntry.supported(r'ImageStyler.$height'),
  SchemaInventoryEntry.supported(r'ImageStyler.$image'),
  SchemaInventoryEntry.supported(r'ImageStyler.$isAntiAlias'),
  SchemaInventoryEntry.supported(r'ImageStyler.$matchTextDirection'),
  SchemaInventoryEntry.supported(r'ImageStyler.$modifier'),
  SchemaInventoryEntry.supported(r'ImageStyler.$repeat'),
  SchemaInventoryEntry.supported(r'ImageStyler.$semanticLabel'),
  SchemaInventoryEntry.supported(r'ImageStyler.$variants'),
  SchemaInventoryEntry.supported(r'ImageStyler.$width'),
  SchemaInventoryEntry.supported(r'StackBoxStyler.$animation'),
  SchemaInventoryEntry.supported(r'StackBoxStyler.$box'),
  SchemaInventoryEntry.supported(r'StackBoxStyler.$modifier'),
  SchemaInventoryEntry.supported(r'StackBoxStyler.$stack'),
  SchemaInventoryEntry.supported(r'StackBoxStyler.$variants'),
  SchemaInventoryEntry.supported(r'StackStyler.$alignment'),
  SchemaInventoryEntry.supported(r'StackStyler.$animation'),
  SchemaInventoryEntry.supported(r'StackStyler.$clipBehavior'),
  SchemaInventoryEntry.supported(r'StackStyler.$fit'),
  SchemaInventoryEntry.supported(r'StackStyler.$modifier'),
  SchemaInventoryEntry.supported(r'StackStyler.$textDirection'),
  SchemaInventoryEntry.supported(r'StackStyler.$variants'),
  SchemaInventoryEntry.supported(r'TextStyler.$animation'),
  SchemaInventoryEntry.supported(r'TextStyler.$maxLines'),
  SchemaInventoryEntry.supported(r'TextStyler.$modifier'),
  SchemaInventoryEntry.supported(r'TextStyler.$overflow'),
  SchemaInventoryEntry.supported(r'TextStyler.$selectionColor'),
  SchemaInventoryEntry.supported(r'TextStyler.$semanticsLabel'),
  SchemaInventoryEntry.supported(r'TextStyler.$softWrap'),
  SchemaInventoryEntry.supported(r'TextStyler.$style'),
  SchemaInventoryEntry.supported(r'TextStyler.$textAlign'),
  SchemaInventoryEntry.supported(r'TextStyler.$textDirection'),
  SchemaInventoryEntry.supported(r'TextStyler.$textDirectives'),
  SchemaInventoryEntry.supported(r'TextStyler.$textHeightBehavior'),
  SchemaInventoryEntry.supported(r'TextStyler.$variants'),
  SchemaInventoryEntry.supported('animation:CurveAnimationConfig'),
  SchemaInventoryEntry.supported(r'config:WidgetModifierConfig.$modifiers'),
  SchemaInventoryEntry.supported('curve:bounceIn'),
  SchemaInventoryEntry.supported('curve:bounceInOut'),
  SchemaInventoryEntry.supported('curve:bounceOut'),
  SchemaInventoryEntry.supported('curve:decelerate'),
  SchemaInventoryEntry.supported('curve:ease'),
  SchemaInventoryEntry.supported('curve:easeIn'),
  SchemaInventoryEntry.supported('curve:easeInBack'),
  SchemaInventoryEntry.supported('curve:easeInCirc'),
  SchemaInventoryEntry.supported('curve:easeInCubic'),
  SchemaInventoryEntry.supported('curve:easeInExpo'),
  SchemaInventoryEntry.supported('curve:easeInOut'),
  SchemaInventoryEntry.supported('curve:easeInOutBack'),
  SchemaInventoryEntry.supported('curve:easeInOutCirc'),
  SchemaInventoryEntry.supported('curve:easeInOutCubic'),
  SchemaInventoryEntry.supported('curve:easeInOutCubicEmphasized'),
  SchemaInventoryEntry.supported('curve:easeInOutExpo'),
  SchemaInventoryEntry.supported('curve:easeInOutQuad'),
  SchemaInventoryEntry.supported('curve:easeInOutQuart'),
  SchemaInventoryEntry.supported('curve:easeInOutQuint'),
  SchemaInventoryEntry.supported('curve:easeInOutSine'),
  SchemaInventoryEntry.supported('curve:easeInQuad'),
  SchemaInventoryEntry.supported('curve:easeInQuart'),
  SchemaInventoryEntry.supported('curve:easeInQuint'),
  SchemaInventoryEntry.supported('curve:easeInSine'),
  SchemaInventoryEntry.supported('curve:easeInToLinear'),
  SchemaInventoryEntry.supported('curve:easeOut'),
  SchemaInventoryEntry.supported('curve:easeOutBack'),
  SchemaInventoryEntry.supported('curve:easeOutCirc'),
  SchemaInventoryEntry.supported('curve:easeOutCubic'),
  SchemaInventoryEntry.supported('curve:easeOutExpo'),
  SchemaInventoryEntry.supported('curve:easeOutQuad'),
  SchemaInventoryEntry.supported('curve:easeOutQuart'),
  SchemaInventoryEntry.supported('curve:easeOutQuint'),
  SchemaInventoryEntry.supported('curve:easeOutSine'),
  SchemaInventoryEntry.supported('curve:elasticIn'),
  SchemaInventoryEntry.supported('curve:elasticInOut'),
  SchemaInventoryEntry.supported('curve:elasticOut'),
  SchemaInventoryEntry.supported('curve:fastEaseInToSlowEaseOut'),
  SchemaInventoryEntry.supported('curve:fastLinearToSlowEaseIn'),
  SchemaInventoryEntry.supported('curve:fastOutSlowIn'),
  SchemaInventoryEntry.supported('curve:linear'),
  SchemaInventoryEntry.supported('curve:linearToEaseOut'),
  SchemaInventoryEntry.supported('curve:slowMiddle'),
  SchemaInventoryEntry.supported('directive:capitalize'),
  SchemaInventoryEntry.supported('directive:lowercase'),
  SchemaInventoryEntry.supported('directive:sentence_case'),
  SchemaInventoryEntry.supported('directive:title_case'),
  SchemaInventoryEntry.supported('directive:uppercase'),
  SchemaInventoryEntry.supported('enum:Axis'),
  SchemaInventoryEntry.supported('enum:BlendMode'),
  SchemaInventoryEntry.supported('enum:BorderStyle'),
  SchemaInventoryEntry.supported('enum:BoxFit'),
  SchemaInventoryEntry.supported('enum:BoxShape'),
  SchemaInventoryEntry.supported('enum:Brightness'),
  SchemaInventoryEntry.supported('enum:Clip'),
  SchemaInventoryEntry.supported('enum:CrossAxisAlignment'),
  SchemaInventoryEntry.supported('enum:FilterQuality'),
  SchemaInventoryEntry.supported('enum:FlexFit'),
  SchemaInventoryEntry.supported('enum:FontStyle'),
  SchemaInventoryEntry.supported('enum:FontWeight'),
  SchemaInventoryEntry.supported('enum:ImageRepeat'),
  SchemaInventoryEntry.supported('enum:MainAxisAlignment'),
  SchemaInventoryEntry.supported('enum:MainAxisSize'),
  SchemaInventoryEntry.supported('enum:StackFit'),
  SchemaInventoryEntry.supported('enum:TextAlign'),
  SchemaInventoryEntry.supported('enum:TextBaseline'),
  SchemaInventoryEntry.supported('enum:TextDecorationStyle'),
  SchemaInventoryEntry.supported('enum:TextDirection'),
  SchemaInventoryEntry.supported('enum:TextLeadingDistribution'),
  SchemaInventoryEntry.supported('enum:TextOverflow'),
  SchemaInventoryEntry.supported('enum:VerticalDirection'),
  SchemaInventoryEntry.supported('enum:WidgetState'),
  SchemaInventoryEntry.supported(r'mix:BaseShadowMix.$blurRadius'),
  SchemaInventoryEntry.supported(r'mix:BaseShadowMix.$color'),
  SchemaInventoryEntry.supported(r'mix:BaseShadowMix.$offset'),
  SchemaInventoryEntry.supported(r'mix:BorderMix.$left'),
  SchemaInventoryEntry.supported(r'mix:BorderMix.$right'),
  SchemaInventoryEntry.supported(r'mix:BorderRadiusMix.$bottomLeft'),
  SchemaInventoryEntry.supported(r'mix:BorderRadiusMix.$bottomRight'),
  SchemaInventoryEntry.supported(r'mix:BorderRadiusMix.$topLeft'),
  SchemaInventoryEntry.supported(r'mix:BorderRadiusMix.$topRight'),
  SchemaInventoryEntry.supported(r'mix:BorderSideMix.$color'),
  SchemaInventoryEntry.supported(r'mix:BorderSideMix.$strokeAlign'),
  SchemaInventoryEntry.supported(r'mix:BorderSideMix.$style'),
  SchemaInventoryEntry.supported(r'mix:BorderSideMix.$width'),
  SchemaInventoryEntry.supported(r'mix:BoxBorderMix.$bottom'),
  SchemaInventoryEntry.supported(r'mix:BoxBorderMix.$top'),
  SchemaInventoryEntry.supported(r'mix:BoxConstraintsMix.$maxHeight'),
  SchemaInventoryEntry.supported(r'mix:BoxConstraintsMix.$maxWidth'),
  SchemaInventoryEntry.supported(r'mix:BoxConstraintsMix.$minHeight'),
  SchemaInventoryEntry.supported(r'mix:BoxConstraintsMix.$minWidth'),
  SchemaInventoryEntry.supported(r'mix:BoxDecorationMix.$backgroundBlendMode'),
  SchemaInventoryEntry.supported(r'mix:BoxDecorationMix.$border'),
  SchemaInventoryEntry.supported(r'mix:BoxDecorationMix.$borderRadius'),
  SchemaInventoryEntry.supported(r'mix:BoxDecorationMix.$shape'),
  SchemaInventoryEntry.supported(r'mix:BoxShadowMix.$spreadRadius'),
  SchemaInventoryEntry.supported(r'mix:DecorationMix.$boxShadow'),
  SchemaInventoryEntry.supported(r'mix:DecorationMix.$color'),
  SchemaInventoryEntry.supported(r'mix:EdgeInsetsGeometryMix.$bottom'),
  SchemaInventoryEntry.supported(r'mix:EdgeInsetsGeometryMix.$top'),
  SchemaInventoryEntry.supported(r'mix:EdgeInsetsMix.$left'),
  SchemaInventoryEntry.supported(r'mix:EdgeInsetsMix.$right'),
  SchemaInventoryEntry.supported(r'mix:StackMix.$alignment'),
  SchemaInventoryEntry.supported(r'mix:StackMix.$clipBehavior'),
  SchemaInventoryEntry.supported(r'mix:StackMix.$fit'),
  SchemaInventoryEntry.supported(r'mix:StackMix.$textDirection'),
  SchemaInventoryEntry.supported(
    r'mix:TextHeightBehaviorMix.$applyHeightToFirstAscent',
  ),
  SchemaInventoryEntry.supported(
    r'mix:TextHeightBehaviorMix.$applyHeightToLastDescent',
  ),
  SchemaInventoryEntry.supported(
    r'mix:TextHeightBehaviorMix.$leadingDistribution',
  ),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$backgroundColor'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$color'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$decoration'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$decorationColor'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$decorationStyle'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$decorationThickness'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$fontFamily'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$fontSize'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$fontStyle'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$fontWeight'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$height'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$letterSpacing'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$shadows'),
  SchemaInventoryEntry.supported(r'mix:TextStyleMix.$wordSpacing'),
  SchemaInventoryEntry.supported('modifier:BlurModifierMix'),
  SchemaInventoryEntry.supported('modifier:DefaultTextStyleModifierMix'),
  SchemaInventoryEntry.supported('modifier:FlexibleModifierMix'),
  SchemaInventoryEntry.supported('modifier:OpacityModifierMix'),
  SchemaInventoryEntry.supported('variant:BreakpointVariant'),
  SchemaInventoryEntry.supported('variant:BrightnessVariant'),
  SchemaInventoryEntry.supported('variant:NamedVariant'),
  SchemaInventoryEntry.supported('variant:NotVariant'),
  SchemaInventoryEntry.supported('variant:WidgetStateVariant'),
  SchemaInventoryEntry.supported('variant_factory:ContextVariant.brightness'),
  SchemaInventoryEntry.supported('variant_factory:ContextVariant.widgetState'),
  SchemaInventoryEntry.supported('variant_factory:Variant.named'),
];

const _phase3DeferredInventory = <SchemaInventoryEntry>[
  SchemaInventoryEntry.knownUnsupported('token:BorderSideToken', _phase3Tokens),
  SchemaInventoryEntry.knownUnsupported('token:BoxShadowToken', _phase3Tokens),
  SchemaInventoryEntry.knownUnsupported('token:BreakpointToken', _phase3Tokens),
  SchemaInventoryEntry.knownUnsupported('token:ColorToken', _phase3Tokens),
  SchemaInventoryEntry.knownUnsupported('token:DoubleToken', _phase3Tokens),
  SchemaInventoryEntry.knownUnsupported('token:DurationToken', _phase3Tokens),
  SchemaInventoryEntry.knownUnsupported('token:FontWeightToken', _phase3Tokens),
  SchemaInventoryEntry.knownUnsupported('token:RadiusToken', _phase3Tokens),
  SchemaInventoryEntry.knownUnsupported('token:ShadowToken', _phase3Tokens),
  SchemaInventoryEntry.knownUnsupported('token:SpaceToken', _phase3Tokens),
  SchemaInventoryEntry.knownUnsupported('token:TextStyleToken', _phase3Tokens),
  SchemaInventoryEntry.knownUnsupported(
    'variant_factory:ContextVariant.desktop',
    _phase3Tokens,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'variant_factory:ContextVariant.mobile',
    _phase3Tokens,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'variant_factory:ContextVariant.tablet',
    _phase3Tokens,
  ),
];

const _phase4DeferredInventory = <SchemaInventoryEntry>[
  SchemaInventoryEntry.knownUnsupported(
    r'BoxStyler.$foregroundDecoration',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'IconStyler.$shadows',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'ImageStyler.$centerSlice',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(r'TextStyler.$locale', _phase4Coverage),
  SchemaInventoryEntry.knownUnsupported(
    r'TextStyler.$strutStyle',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'TextStyler.$textScaler',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'TextStyler.$textWidthBasis',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'animation:SpringAnimationConfig',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_alpha',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_brighten',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_darken',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_desaturate',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_lighten',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_opacity',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_saturate',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_shade',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_tint',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_with_blue',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_with_green',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_with_red',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:color_with_values',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:number_abs',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:number_add',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:number_ceil',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:number_clamp',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:number_divide',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:number_floor',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:number_multiply',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:number_round',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'directive:number_subtract',
    _phase4Directives,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'enum:ElevationShadow',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported('enum:Orientation', _phase4Variants),
  SchemaInventoryEntry.knownUnsupported('enum:TargetPlatform', _phase4Variants),
  SchemaInventoryEntry.knownUnsupported('enum:TextWidthBasis', _phase4Coverage),
  SchemaInventoryEntry.knownUnsupported('enum:TileMode', _phase4Coverage),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:BeveledRectangleBorderMix.$borderRadius',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:BorderDirectionalMix.$end',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:BorderDirectionalMix.$start',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:BorderRadiusDirectionalMix.$bottomEnd',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:BorderRadiusDirectionalMix.$bottomStart',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:BorderRadiusDirectionalMix.$topEnd',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:BorderRadiusDirectionalMix.$topStart',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:CircleBorderMix.$eccentricity',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:ContinuousRectangleBorderMix.$borderRadius',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:DecorationImageMix.$alignment',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:DecorationImageMix.$centerSlice',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:DecorationImageMix.$filterQuality',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:DecorationImageMix.$fit',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:DecorationImageMix.$image',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:DecorationImageMix.$invertColors',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:DecorationImageMix.$isAntiAlias',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:DecorationImageMix.$repeat',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:DecorationMix.$gradient',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:DecorationMix.$image',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:EdgeInsetsDirectionalMix.$end',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:EdgeInsetsDirectionalMix.$start',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:GradientMix.$colors',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:GradientMix.$stops',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:GradientMix.$transform',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:LinearBorderEdgeMix.$alignment',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:LinearBorderEdgeMix.$size',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:LinearBorderMix.$bottom',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:LinearBorderMix.$end',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:LinearBorderMix.$start',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:LinearBorderMix.$top',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:LinearGradientMix.$begin',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:LinearGradientMix.$end',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:LinearGradientMix.$tileMode',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:OutlinedBorderMix.$side',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:RadialGradientMix.$center',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:RadialGradientMix.$focal',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:RadialGradientMix.$focalRadius',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:RadialGradientMix.$radius',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:RadialGradientMix.$tileMode',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:RoundedRectangleBorderMix.$borderRadius',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:RoundedSuperellipseBorderMix.$borderRadius',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:ShapeDecorationMix.$shape',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StarBorderMix.$innerRadiusRatio',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StarBorderMix.$pointRounding',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StarBorderMix.$points',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StarBorderMix.$rotation',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StarBorderMix.$squash',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StarBorderMix.$valleyRounding',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StrutStyleMix.$fontFamily',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StrutStyleMix.$fontFamilyFallback',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StrutStyleMix.$fontSize',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StrutStyleMix.$fontStyle',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StrutStyleMix.$fontWeight',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StrutStyleMix.$forceStrutHeight',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StrutStyleMix.$height',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:StrutStyleMix.$leading',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:SweepGradientMix.$center',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:SweepGradientMix.$endAngle',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:SweepGradientMix.$startAngle',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:SweepGradientMix.$tileMode',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:TextStyleMix.$debugLabel',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:TextStyleMix.$fontFamilyFallback',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:TextStyleMix.$textBaseline',
    _phase4Coverage,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:AlignModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:AspectRatioModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:BoxModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:ClipOvalModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:ClipRRectModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:ClipRectModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:ClipTriangleModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:DefaultTextStylerModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:FractionallySizedBoxModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:IconThemeModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:IntrinsicHeightModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:IntrinsicWidthModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:PaddingModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:RotateModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:RotatedBoxModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:ScaleModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:ScrollViewModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:SizedBoxModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:SkewModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:TransformModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:TranslateModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:VisibilityModifierMix',
    _phase4Modifiers,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'variant_factory:ContextVariant.breakpoint',
    _phase4Variants,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'variant_factory:ContextVariant.directionality',
    _phase4Variants,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'variant_factory:ContextVariant.not',
    _phase4Variants,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'variant_factory:ContextVariant.orientation',
    _phase4Variants,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'variant_factory:ContextVariant.platform',
    _phase4Variants,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'variant_factory:ContextVariant.web',
    _phase4Variants,
  ),
];

const _neverUnsupportedInventory = <SchemaInventoryEntry>[
  SchemaInventoryEntry.knownUnsupported(
    'animation:KeyframeAnimationConfig',
    _neverClosureBacked,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'animation:PhaseAnimationConfig',
    _neverClosureBacked,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'config:WidgetModifierConfig.$orderOfModifiers',
    _neverInternal,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'enum:ListMergeStrategy',
    _neverInternal,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:TextStyleMix.$background',
    'never: Paint is runtime-only and not JSON representable.',
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:TextStyleMix.$fontFeatures',
    _neverRuntimeOnly,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:TextStyleMix.$fontVariations',
    _neverRuntimeOnly,
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:TextStyleMix.$foreground',
    'never: Paint is runtime-only and not JSON representable.',
  ),
  SchemaInventoryEntry.knownUnsupported(
    r'mix:TextStyleMix.$inherit',
    _neverInternal,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:ClipPathModifierMix',
    _neverRuntimeOnly,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:MouseCursorModifierMix',
    _neverRuntimeOnly,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:ResetModifierMix',
    _neverInternal,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'modifier:ShaderMaskModifierMix',
    _neverClosureBacked,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'token:ContextToken',
    _neverRuntimeOnly,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'variant:ContextVariant',
    _neverClosureBacked,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'variant:ContextVariantBuilder',
    _neverClosureBacked,
  ),
  SchemaInventoryEntry.knownUnsupported(
    'variant_factory:ContextVariant.size',
    _neverClosureBacked,
  ),
];
