name: "Add labels"

on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const files = context.payload.pull_request.files
            console.log(`Modified files on this PR: ${files}`)

