name: "Add labels"

on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const files = context.payload.pull_request.files
            console.log(`Modified files on this PR: ${files}`)

            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })
