name: Analyze Workflow

on:
  push:
  pull_request_target:
    branches: [main]
    paths-ignore:
      - 'scripts/**'
      - 'website/**'
      - 'assets/**'

jobs:
  dcm:
    name: DCM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mix repo
        uses: actions/checkout@v4
      
      - name: Setup FVM
        uses: ./.github/actions/fvm/
        with:
          flutter-version: 'stable'

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3

      - name: Run build runner
        shell: bash    
        run: melos run brb

      - name: Install DCM
        uses: CQLabs/setup-dcm@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DCM
        uses: CQLabs/dcm-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folders: packages/*/lib
          ci_key: oss
          email: oss
          fatal_style: true
          fatal_performance: true
          fatal_warnings: true

      - name: dart analyze
        run: melos analyze
        shell: bash
      
      - name: Run custom_lint
        run: melos run custom_lint_analyze
        shell: bash
        