name: Changelog

on:
  workflow_dispatch:
    inputs:
      mix:
        type: string
        description: set specific version for mix
        default: ""
      mix_lint:
        type: string
        description: set specific version for mix_lint
        default: ""
      mix_annotations:
        type: string
        description: set specific version for mix_annotations
        default: ""
      mix_generator:
        type: string
        description: set specific version for mix_generator
        default: ""

jobs:
  version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install FVM
      shell: bash
      run: |
        curl -fsSL https://fvm.app/install.sh | bash
        fvm use mincompat --force
        
    - uses: kuhnroyal/flutter-fvm-config-action@v2
      id: fvm-config-action

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

    - name: Flutter version
      shell: bash
      run: |
        flutter --version
        
    - name: Setup Melos
      run: |
        dart pub global activate melos
        melos bs

    - name: Configure Git User
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Creating the new version

      run: |
        git checkout -b release/package-versions
        git push --set-upstream origin release/package-versions

        packages_with_versions=""

        if [ "${{ github.event.inputs.mix }}" != "" ]; then
          packages_with_versions="$packages_with_versions -V mix:${{ github.event.inputs.mix }}"
        fi
        if [ "${{ github.event.inputs.mix_lint }}" != "" ]; then
          packages_with_versions="$packages_with_versions -V mix_lint:${{ github.event.inputs.mix_lint }}"
        fi
        if [ "${{ github.event.inputs.mix_annotations }}" != "" ]; then
          packages_with_versions="$packages_with_versions -V mix_annotations:${{ github.event.inputs.mix_annotations }}"
        fi
        if [ "${{ github.event.inputs.mix_generator }}" != "" ]; then
          packages_with_versions="$packages_with_versions -V mix_generator:${{ github.event.inputs.mix_generator }}"
        fi

        melos version --yes --no-git-tag-version $packages_with_versions

        git push --follow-tags
        gh pr create --title "chore: version packages" --body "This PR was opened by the changelog GitHub Actions workflow" --reviewer leoafarias
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}