name: Changelog

on:
  workflow_dispatch:

jobs:

  version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install FVM
      shell: bash
      run: |
        curl -fsSL https://fvm.app/install.sh | bash
        fvm use stable --force

    - uses: kuhnroyal/flutter-fvm-config-action@v2
      id: fvm-config-action

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

    - name: Flutter version
      shell: bash
      run: flutter --version
        
    - name: Setup Melos
      uses: bluefireteam/melos-action@v3

    - name: Run melos version
      run: melos run fix

    - name: Run melos version
      run: melos version --yes
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: version packages'
        title: 'chore: version packages'
        body: 'This PR was opened by the changelog GitHub Actions workflow'
        branch: 'create-pull-request/package-versions'
